export enum Categorie {
  IGNORE = "IGNORE",
  SAVE_NOTE = "SAVE_NOTE",
  DELETE = "DELETE",
  INSULIN_NPH = "INSULIN_NPH",
  INSULIN_R = "INSULIN_R",
  INSULIN_UR = "INSULIN_UR",
  GLUCOSE = "GLUCOSE",
  SPELLED_HIGH_GLUCOSE = "SPELLED_HIGH_GLUCOSE",
  SPELLED_LOW_GLUCOSE = "SPELLED_LOW_GLUCOSE",
  BREAKFAST = "BREAKFAST",
  LUNCH = "LUNCH",
  SNACK = "SNACK",
  DINNER = "DINNER",
  FREE_MEAL = "FREE_MEAL",
  COMPENSATORY_MEAL = "COMPENSATORY_MEAL",
  GYM = "GYM",
  STRENGTH_TRAINING = "STRENGTH_TRAINING",
  AEROBIC_EXERCISE = "AEROBIC_EXERCISE",
  INDEFINITE = "INDEFINITE",
}

export interface Record {
  dirtyToken: string;
  token: string;
  categorie: Categorie;
  time?: Date;
}
